-- Auto-generated by export_data.py — Jake's spreadsheet notes as comments.
-- Safe to run once in phpMyAdmin after schema.sql. Re-running skips duplicates.

INSERT INTO comments (player, author, text, created_at)
SELECT 'George Kittle', 'Ryan', 'Major performance dip due to Injury', '2026-08-19 17:11:13'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'George Kittle' AND text = 'Major performance dip due to Injury');
INSERT INTO comments (player, author, text, created_at)
SELECT 'Nico Collins', 'Ryan', 'Houston WR room is thing. Expect heavy workload for Collins.', '2026-08-19 17:17:11'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'Nico Collins' AND text = 'Houston WR room is thing. Expect heavy workload for Collins.');
INSERT INTO comments (player, author, text, created_at)
SELECT 'Ladd McConkey', 'Ryan', 'New OC (Mike McDaniels, exp to be #1 WR Target)', '2026-08-21 14:55:00'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'Ladd McConkey' AND text = 'New OC (Mike McDaniels, exp to be #1 WR Target)');
INSERT INTO comments (player, author, text, created_at)
SELECT 'Tyler Shough', 'Ryan', 'Good Preseason and Camp. Stock rising', '2026-08-19 17:15:06'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'Tyler Shough' AND text = 'Good Preseason and Camp. Stock rising');
INSERT INTO comments (player, author, text, created_at)
SELECT 'Luther Burden', 'Ryan', 'Playing through minor injury', '2026-08-19 17:12:09'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'Luther Burden' AND text = 'Playing through minor injury');
INSERT INTO comments (player, author, text, created_at)
SELECT 'Malik Nabers', 'Ryan', 'Likely will play wk 1. Wk 4 ramp up.', '2026-08-19 17:13:05'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'Malik Nabers' AND text = 'Likely will play wk 1. Wk 4 ramp up.');
INSERT INTO comments (player, author, text, created_at)
SELECT 'Jordyn Tyson', 'Ryan', 'Severe Hamstring Injury', '2026-08-19 17:10:27'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'Jordyn Tyson' AND text = 'Severe Hamstring Injury');
INSERT INTO comments (player, author, text, created_at)
SELECT 'Makai Lemon', 'Ryan', '2nd Hamstring Injury. Expect dip in stats', '2026-08-19 17:14:22'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'Makai Lemon' AND text = '2nd Hamstring Injury. Expect dip in stats');
INSERT INTO comments (player, author, text, created_at)
SELECT 'KC Concepcion', 'Ryan', 'More hype around preseason', '2026-08-21 14:42:02'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'KC Concepcion' AND text = 'More hype around preseason');
INSERT INTO comments (player, author, text, created_at)
SELECT 'De''Zhaun Stribling', 'Ryan', 'USE TOP ROOKIE PICK IF POSSIBLE', '2026-08-21 14:56:47'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'De''Zhaun Stribling' AND text = 'USE TOP ROOKIE PICK IF POSSIBLE');
INSERT INTO comments (player, author, text, created_at)
SELECT 'Cyrus Allen', 'Ryan', 'Preseason and Camp high praise', '2026-08-19 17:43:35'
WHERE NOT EXISTS (SELECT 1 FROM comments WHERE player = 'Cyrus Allen' AND text = 'Preseason and Camp high praise');
